steps:
  - label: "Create conda env"
    key: "conda"
    command: bash .buildkite/install-env.sh

  - label: ":pip: Install dependencies and LMCache"
    key: "pip"
    depends_on: ["conda"]
    command: bash .buildkite/install-packages.sh

# - label: Lint with Ruff
#   depends_on: ["pip"]
#   command: |
#     pip install ruff
#     ruff check .
#   plugins:
#     - docker#v5.9.0:
#         image: "python:3.13"

  - label: ":pytest: Run pytest"
    key: "pytest"
    depends_on: ["pip"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkite
      pytest --junitxml=junit/test-results.xml \
    artifact_paths:
      - junit/test-results.xml

  - label: ":junit: Annotate"
    depends_on: ["pytest"]
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: junit/*.xml

  - wait: ~
    continue_on_failure: true
    depends_on: ["conda"]
    allow_dependency_failure: false

  - label: "Clean up"
    command: bash .buildkite/cleanup.sh
