steps:
  - label: ":pip: Prepare conda env and prerequisites"
    key: "conda"
    command: bash .buildkite/install-env.sh

  - label: ":pytest: Run pytest"
    key: "pytest"
    depends_on: ["conda"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkite
      bash .buildkite/install-lmcache.sh
      coverage run --source=lmcache/ -m pytest -v --junitxml=junit/test-results.xml 
      coverage report -m > coverage.report
    artifact_paths:
      - junit/test-results.xml
      - coverage.report

  - label: ":junit: Annotate"
    depends_on: ["pytest"]
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: junit/*.xml

