steps:
  - label: "Create conda env"
    key: "conda"
    command: bash .buildkite/install-env.sh

  - label: ":pip: Install dependencies and LMCache"
    key: "pip"
    depends_on: ["conda"]
    command: bash .buildkite/install-packages.sh

  - label: ":pytest: Run pytest"
    key: "pytest"
    depends_on: ["pip"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkite
      bash .buildkite/install-lmcache.sh
      pytest --junitxml=junit/test-results.xml \
    artifact_paths:
      - junit/test-results.xml
    plugins:
      - test-collector#v1.0.0:
          files: "junit/*.xml"
          format: "junit"

  - label: ":junit: Annotate"
    depends_on: ["pytest"]
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: junit/*.xml

