steps:
  - label: "Create conda env"
    key: "conda"
    command: |
      source ${HOME}/.bashrc
      conda create -n buildkit python=3.10 -y 
      eval "$(conda shell.bash hook)"
      conda activate buildkit

  - label: ":pip: Install dependencies"
    key: "pip"
    depends_on: ["conda"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkit
      pip install -r requirements.txt

  - label: ":pip: Install test dependencies"
    key: "pip-test"
    depends_on: ["pip"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkit
      pip install -r requirements-test.txt

# - label: Lint with Ruff
#   depends_on: ["pip"]
#   command: |
#     pip install ruff
#     ruff check .
#   plugins:
#     - docker#v5.9.0:
#         image: "python:3.13"

  - label: ":pytest: Run pytest"
    key: "pytest"
    depends_on: ["pip", "pip-test"]
    command: |
      eval "$(conda shell.bash hook)"
      conda activate buildkit
      pytest --junitxml=junit/test-results.xml \
    artifact_paths:
      - junit/test-results.xml

  - label: ":junit: Annotate"
    depends_on: ["pytest"]
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: junit/*.xml

  - wait: ~
    continue_on_failure: true
    depends_on: ["conda"]
    allow_dependency_failure: false

  - label: "Clean up"
    command: conda env remove -n buildkit
